import Layout from '../components/Layout';
import Link from 'next/link';
import Head from 'next/head';
import { useState } from 'react';
import { useSession, signOut, getSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();
  function handleSignOut() {
    signOut()
  }

  return (
    <>
      <Head>
        <title>User Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/morty.png" />
      </Head>

      {session ? <User session={session} handleSignOut={handleSignOut} /> : <Guest />}
    </>
  );
}

// Guest
function Guest() {
  return (
    <main className="container mx-auto text-center py-20">
      <h3 className="text-4xl font-bold">Guest Hompage</h3>
      <div className="flex justify-center">
        <Link href={'/login'} className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50">
          Sign In
        </Link>
      </div>
    </main>
  );
}

// User
function User({ session, handleSignOut }) {
  return (
    <main className="container mx-auto text-center py-20">
      <h3 className="text-4xl font-bold">Authorize User Hompage</h3>

      <div className="details">
        <h5>{session.user.name}</h5>
        <h5>{session.user.email}</h5>
      </div>

      <div className="flex justify-center">
        <button
          className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
          onClick={handleSignOut}>
          Sign Out
        </button>
      </div>
    </main>
  );
}

export async function getServerSideProps(context) {
  const { req } = context;
  const session = await getSession({
    req,
  });

  // if user isn't is auth
  if (!session) return { redirect: { destination: 'https://user-auth-ivory.vercel.app/login', permanent: false } };

  // if user is is auth
  return {
    props: { session },
  };
}
